### ISSUE TITLE
subPARC graph weight calculation

### ISSUE THREAD

**Issue by GreenGilad** [ShobiStassen/VIA#14]
Hi again,

I am going through the code of `run_subPARC` and notice that:

- When calling the `make_csrmatrix_noselfloop` function, the edge weights are calculated using `1. / distances + 0.01`
- Later in the `run_subPARC`, in case `is_course == True` you create a full (unpruned) graph but calculate the weights using `1./distances + 0.05`.

Is there a specific reason why we would want these values to be different? (It changes the weight values quiet a bit)

**Comment by ShobiStassen** [comment]
hi, the graph made in the make_csrmatric_noselfloop function gives the csr matrix (csr_array_locallypruned) where we have distance + 0.01. This graph is used for clustering only and not for the random walk functions. The clusters derived from this stage are then used as the labels in the vertex graph constructed later (as ig_full_graph)

We create a second graph that is used for the random walk (pseudotime) purposes that is created with the distance +0.05 factor. This is the ig_full_graph (csr_full_graph in csr form, or igraph format in the ig_full_graph case) which is used for randomwalk related functions. If the edgeweights are very high (in the case where you have a very small distance between two nodes) then they disproportionately dominate the randomwalk simulations and prevent certain allowable paths to occur within the span of the 1000 or so MCMC simulations that are run. If there are some very weak edges, which may have been spuriously weak or truly weak,the simulations will never reach these nodes because the higher weight edges are too dominant. We therefore truncate the allowable range of values so that the difference between strong edges and weak ones does not overly distort the potential pathways that can be found in a fairly "small" number of simulations. One might be able to lower this value a bit more, but based on all the various datasets we tested, this small additive value of 0.05 for the randomwalk graphs worked reasonably. This graph is saved and then used again for the fine-grained iteration of VIA (when is_course == False), should you decide to feed the first coarse run of VIA into a second finer grained one. 
The rationale for running a coarse and then fine grained VIA is that the terminal states detected in the coarse run, are usually adequate, whereas doing a very fine grained run can give you better resolution of the pseudotime and pathway probabilities, but can also potentially suggest too many terminal states.
