### ISSUE TITLE
sum of lineage probability

### ISSUE THREAD

**Issue by wangjiawen2013** [ShobiStassen/VIA#33]
Hi,
The sum of branch probability given Palantir equals 1. It's accord with the principle of statistics. while I find the sum of branch probability given by VIA don't eqaul 1, how to interpret this probability ?
![image](https://user-images.githubusercontent.com/29703450/208403495-356ff105-583b-46ef-9f1d-de25628eda27.png)

**Comment by ShobiStassen** [comment]
Hi, at the cluster level the probabilities given in Via will sum to 1
across the rows. (Like what you see in palantir)
However after computing the single cell probabilities, we column normalise
the values so that probabilities for  rare lineages can also be better
visually examined. This is useful for rare lineages that are very rarely
arrived at but for which we still want to see pathways.
I can later next week when I'm backalso add an attribute so that the non
normalized single cell prob can be extracted as an attribute
