### ISSUE TITLE
FileNotFoundError in VIA(embedding_type='via-umap')

### ISSUE THREAD

**Issue by searchlie** [ShobiStassen/VIA#43]
Hi, 

I am running [Basic workflow](https://pyvia.readthedocs.io/en/latest/ViaJupyter_Toy_Multifurcating.html?highlight=via-umap#Parameters) and encountering the following error.

![image](https://github.com/ShobiStassen/VIA/assets/28975498/b79a4089-6d5f-401b-80ff-99f8dad19192)

Looking at the source code, the following line seems to be causing the error

https://github.com/ShobiStassen/VIA/blob/7e69c84b84385b9fbe914793279b2edeff35ab7a/VIA/core.py#L1942

I can't imagine what is going on around this line. Why is it necessary to load the zebrafish dataset when running UMAP?

Note that changing embedding_type="via-mds" worked fine.

**Comment by ShobiStassen** [comment]
Hi,
Sorry about this, it's a bug and the line on the zebrafish dataset should not be there. 
I'll upload a fixed version onto pip so you can reinstall via. In order to get more control over the via-umap and via-mds plots, i would suggest trying to compute the embeddings after running the main via function (this is also shown in the basic workflow tutorial by code section 8) so you can tune parameters like min_dist = (value from 0.1-0.5 usually reasonable) and init_pos = 'via' or 'spectral' when calling via_umap or via_mds separately, in case you want to tune your plots.

**Comment by ShobiStassen** [comment]
hi @searchlie 
just fixed the bug, v0.1.85 should be ok. let me know if it works for you
Shobi

**Comment by searchlie** [comment]
@ShobiStassen 
It worked! Thanks for the quick update.
![image](https://github.com/ShobiStassen/VIA/assets/28975498/57aa5e2a-000f-4094-9512-57949e5103a7)



Also, thanks for the advice about  running via_umap separetely. It worked well too and seems useful!
![image](https://github.com/ShobiStassen/VIA/assets/28975498/739b440d-df08-417f-834c-ef5fe83e6f62)
